### ISSUE TITLE
Adding infix to postfix conversion

### ISSUE THREAD

**Issue by BALASARVAN12** [chandug25/Hacktoberfest2023#17]
I'd like to suggest adding an infix to the postfix Python code.

Please assign this issue to me.

**Comment by gschandrasekhar** [comment]
[THIS REPO IS EXCLUDED FROM HACKTOBERFEST](https://github.com/chandug25/Hacktoberfest2023#this-repo-is-excluded-from-hacktoberfest)  please contribute to other repo's
