### ISSUE TITLE
Addition of Low Level Design of Snake and Ladders Game

### ISSUE THREAD

**Issue by Soumya1219** [chandug25/Hacktoberfest2023#19]
I would like to add low level design of snake and ladder game in java which is very useful for the programmers who want to get hands on practice on OOPS concepts and loops. 

Kindly assign me with this issue :)

**Comment by gschandrasekhar** [comment]
[THIS REPO IS EXCLUDED FROM HACKTOBERFEST](https://github.com/chandug25/Hacktoberfest2023#this-repo-is-excluded-from-hacktoberfest)  please contribute to other repo's
