### ISSUE TITLE
[Feature]: Matrix rain effect [Hackers edition] using vanilla.js

### ISSUE THREAD

**Issue by lordsid003** [chandug25/Hacktoberfest2023#24]
## Feature proposal:
💡Implementation of cool matrix-rain effect inspired by live wallpaper for aesthetic background for webpages. This version is based on stereotypical Hackers' interface.

## Goal:
🎯To harness the potential of javascript and css for custom wallpaper designs

## Implementation:
* Html for canvas loading and structural composition
* CSS for frontend UI design
* Vanilla javascript for bringing life to the project (Animation frames and dynamic elements)

## Prototype Screenshots:
![Screenshot 2023-10-25 230834](https://github.com/chandug25/Hacktoberfest2023/assets/119743101/bd0d2f57-4f9d-47b0-a413-4fdfe574475c)

## Usecase:
* Dynamic Webpage design
* Custom wallpaper design potential using code

**Comment by lordsid003** [comment]
Please review my PR for this issue and add "Hacktoberfest" tag if you find it appropriate.
Thanks

**Comment by gschandrasekhar** [comment]
[THIS REPO IS EXCLUDED FROM HACKTOBERFEST](https://github.com/chandug25/Hacktoberfest2023#this-repo-is-excluded-from-hacktoberfest)  please contribute to other repo's
